[package]
name = "netvars_derive"
version = "0.1.0"
authors = ["Balen <barena.ekusuimii@gmail.com>"]
edition = "2018"

[lib]
proc-macro=true

[dependencies]
proc-macro2 = "1.0.19"
syn = { version = "1.0.35", features = ["full"] }
quote = "1.0.7"